seed: 42
output_dir: roberta-base-ne
dataset:
  portion: "100%"
tokenizer:
  min_frequency: 2
  special_tokens:
                - "<s>"
                - "<pad>"
                - "</s>"
                - "<unk>"
                - "<mask>"
model:
  architecture: roberta-base
  batch_size: 16
  fp16: False
  epochs: 3
  mlm_probability: 0.15